### ISSUE TITLE
Wrong Wording

### ISSUE THREAD

**Issue by psteeve** [SquareBracketAssociates/books.pharo.org#1]
Hi,

There is a wrong wording in the index page section Little Scheme. The wording is about the Spec UI framework. 
I wanted to create a PR to fix the problem but github didn't let me do it because i don't have access. Do you guys accept PR ? 

Thanks for this project, i m a professional web developper in Paris,  if you want help with your website it will be a pleasure for me to contribute. 

Best Regards,

Steeve

**Comment by Ducasse** [comment]
sure please send me a PR.
Thanks a lot.

**Comment by psteeve** [comment]
Could you please tell me the process. When i try to push my branch github tell me that i don't have any access right, and when i try to create the PR it tells me to try another branch other than master.

Thanks for your help.
