### ISSUE TITLE
http://www.pharo.org/books -> books.pharo.org

### ISSUE THREAD

**Issue by hernanmd** [SquareBracketAssociates/books.pharo.org#6]
The URL in https://github.com/SquareBracketAssociates should be updated to https://books.pharo.org/
Currently it points to an empty page.

**Comment by Ducasse** [comment]
Done

**Comment by hxk9614** [comment]
Hi, i test it but it not work

**Comment by MarcusDenker** [comment]
I checked and the link is fixed.
